export const FETCH_PRODUCT = 'products/FETCH_PRODUCT'
export const FETCH_PRODUCTS = 'products/FETCH_PRODUCTS'
export const FETCH_ADMIN_PRODUCTS = 'products/FETCH_ADMIN_PRODUCTS'
export const CREATE_PRODUCT = 'products/CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'products/UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'products/DELETE_PRODUCT'
